sudo: required
services:
  - docker

before_install:
  - docker build -t fatems/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run fatems/react-test npm test -- --coverage

after_success:
  - docker build -t fatems/multi-client ./client
  - docker build -t fatems/multi-nginx ./nginx
  - docker build -t fatems/multi-server ./server
  - docker build -t fatems/multi-worker ./worker

  #log into the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take the images and push to docker hub
  - docker push fatems/multi-client
  - docker push fatems/multi-nginx
  - docker push fatems/multi-server
  - docker push fatems/multi-worker 

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name:  elasticbeanstalk-us-west-1-306476627547
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  