  version: '3'
  services:
    postgres:
      image: 'postgres:latest'
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres_password
        POSTGRES_DB: postgres
    redis:
      image: 'redis:latest'
    nginx:
      restart: always
      build:
        dockerfile: Dockerfile.dev
        context: ./nginx
      ports:
        - '3040:80'
    api:
      build:
        dockerfile: Dockerfile.dev
        context: ./server
      volumes:
        - /app/node_modules 
        - ./server:/app
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - PGUSER=postgres
        - PGHOST=postgres
        - PGDATABASE=postgres
        - PGPASSWORD=postgres_password
        - PGPORT=5432
      depends_on:
      - postgres  # Ensure that postgres service is started before api
      - redis  
    client:
      
      build:
        dockerfile: Dockerfile.dev
        context: ./client
      volumes:
        - ./client:/app 
        - /app/node_modules
      # environment:
      #   - CHOKIDAR_USEPOLLING=true
      # ports:
      #   - "3000:3000"
      # command: npm start -- --host=0.0.0.0
      

    worker:
      build:
        dockerfile: Dockerfile.dev
        context: ./worker
      volumes:
        - /app/node_modules
        - ./worker:/app
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
      depends_on:
        - redis


